
version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: health_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: etl_test
    network_mode: host

  flask_task:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: health_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: etl_test
    volumes:
      - ./logs:/app/logs 
    network_mode: host

